### ISSUE TITLE
Maybe `llm-samplers` could be usefull here

### ISSUE THREAD

**Issue by LLukas22** [EricLBuehler/candle-sampling#1]
Kerfuffle created the [llm-samplers](https://github.com/KerfuffleV2/llm-samplers), which implements some of the most common sampling methods and some more exotic ones (e.g. Mirostat V2), maybe worth looking into.

**Comment by EricLBuehler** [comment]
@LLukas22, thanks! I will check that out, and maybe base some of my implementations on theirs. It looks like they take a slightly different approach with their sampling chains, but I think I will take a look at the implementations.
